name: Build ImmortalWRT VIKINGYFY

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "选择要编译的 ImmortalWRT 分支"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - owrt
      ssh:
        description: 'Enable SSH connection?'
        required: true
        default: 'false'
        type: choice
        options:
          - false
          - true
env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  TZ: Asia/Shanghai
  REPO_URL: https://github.com/VIKINGYFY/immortalwrt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Clone ImmortalWRT source
        run: |
          git clone --depth=1 --single-branch $REPO_URL -b ${{ github.event.inputs.branch }}
          cd immortalwrt
          cp $GITHUB_WORKSPACE/feeds/24.10 ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Start SSH via ngrok
        uses: lbbboy/ssh2actions@main
        with:
          mode: ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_REGION: us
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        if: ${{ github.event.inputs.ssh == 'true' }}
