name: SSH Control Workflow

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Enable SSH connection?'
        required: true
        default: 'false'
        type: choice
        options:
          - false
          - true

jobs:
  ssh-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH connection to Actions
        env:
          TELEGRAM_TOKEN : ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        uses: garypang13/debugger-action@master
        if: ${{ github.event.inputs.ssh == 'true' }}
