name: SSH Control Workflow

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Enable SSH connection?'
        required: true
        default: 'true'
        type: choice
        options:
          - true
          - false        

jobs:
  ssh-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH connection to Actions
        uses: kiddin9/debugger-action@master
        if: ${{ github.event.inputs.ssh == 'true' }}
