name: SSH Control Workflow

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Enable SSH connection?'
        required: true
        default: 'false'
        type: choice
        options:
          - false
          - true
      ngrok:
        description: 'Start SSH via ngrok'
        required: true
        default: 'false'
        type: choice
        options:
          - false
          - true

env:
  TZ: Asia/Shanghai

jobs:
  ssh-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Checkout
        uses: actions/checkout@main

      - name: SSH connection to Actions
        env:
          TELEGRAM_BOT_TOKEN : ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        uses: lbbboy/ssh2actions@main
        if: ${{ github.event.inputs.ssh == 'true' }}

      - name: Start SSH via ngrok
        uses: lbbboy/ssh2actions@main
        with:
          mode: ngrok
        env:
         NGROK_REGION: us
         NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
         SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
         if: ${{ github.event.inputs.ngrok == 'true' }}
